const plants = [
  {
    id: 1,
    name: "Snake Plant (Dracaena trifasciata)",
    image: "/images/snake-plant.jpg",
    description: "Known for their resilience, air-purifying abilities, and low-maintenance nature.",
    light: "Low",
    size: "Large",
    petSafe: false,
    wateringIntervalDays: 14,
    careTips: {
      light: [
        "Snake plants thrive in low to bright indirect light.",
        "Avoid direct sunlight to prevent leaf burn.",
        "Can tolerate fluorescent light—good for offices.",
        "Put it in an east-facing window or near a south- or west-facing window.",
      ],
      watering: "Snake plants should be watered sparingly, allowing the soil to dry out completely between waterings.",
      soil: "A mix that includes perlite, coco coir, and sand to improve drainage.",
      pests: "Watch for mealybugs. Wipe leaves with neem oil.",
      propagation: "Leaf cuttings are a common method.",
    },
  },
  {
    id: 2,
    name: "Spider Plant (Chlorophytum comosum)",
    image: "/images/spider-plant.jpg",
    description: "Fast-growing, tolerant of neglect, and able to thrive in nearly any type of condition.",
    light: "Bright",
    size: "Small",
    petSafe: true,
    wateringIntervalDays: 7,
    careTips: {
      light: [
        "Spider plants thrive in bright, indirect light.",
        "Avoid direct sunlight, which can scorch the leaves.",
        "If you don't have an ideal location, consider using a grow light.",
      ],
      watering: "Water when the top inch of soil is dry—typically once a week.",
      soil: "A mix of potting soil, perlite, and peat moss.",
      pests: "Common pests include spider mites. Use insecticidal soap.",
      propagation: "Cut and root plantlets (spiderettes) in water or soil.",
    },
  },
  {
    id: 3,
    name: "Pothos (Epipremnum aureum)",
    image: "/images/pothos-plant.jpg",
    description: "A hardy vining plant that thrives in a variety of light conditions and grows quickly.",
    light: "Low to Medium",
    size: "Medium",
    petSafe: false,
    wateringIntervalDays: 10,
    careTips: {
      light: [
        "Pothos prefer bright, indirect light but can tolerate low light.",
        "Avoid direct sunlight to prevent leaf burn.",
      ],
      watering: "Water when the top 2 inches of soil feel dry. Do not overwater.",
      soil: "Well-draining potting mix with perlite.",
      pests: "Watch for scale and mealybugs.",
      propagation: "Cut stems just below a node and root in water.",
    },
  },
  {
    id: 4,
    name: "ZZ Plant (Zamioculcas zamiifolia)",
    image: "/images/zz-plant.jpg",
    description: "Ultra low-maintenance with glossy, dark green leaves—perfect for beginners.",
    light: "Low",
    size: "Medium",
    petSafe: false,
    wateringIntervalDays: 21,
    careTips: {
      light: [
        "ZZ plants tolerate low to bright, indirect light.",
        "Avoid direct sun to prevent scorched leaves.",
      ],
      watering: "Let the soil dry out completely between waterings—typically every 2–3 weeks.",
      soil: "Cactus or succulent mix works best.",
      pests: "Rare, but may include aphids or spider mites.",
      propagation: "Divide rhizomes or root stem cuttings in water.",
    },
  },
  {
    id: 5,
    name: "Peace Lily (Spathiphyllum wallisii)",
    image: "/images/peace-lily.jpg",
    description: "Beautiful white blooms and lush foliage. Purifies air and prefers humidity.",
    light: "Medium",
    size: "Medium",
    petSafe: false,
    wateringIntervalDays: 7,
    careTips: {
      light: [
        "Prefers bright, indirect light but tolerates low light.",
        "Too much light may cause leaf tips to brown.",
      ],
      watering: "Keep soil moist, but not soggy. Water about once a week.",
      soil: "Moisture-retentive potting mix with good drainage.",
      pests: "Aphids and spider mites may appear. Use neem oil or soapy water.",
      propagation: "Divide during repotting and plant sections separately.",
    },
  },
];

export default plants;